# Default values for sentry-kubernetes.

sentry:
  dsn: ~
  existingSecret: ~
  logLevel: ~
  environment: ~
  release: ~

  # Sets event filters. If a filter is empty, the filter itself is ignored.
  filters:
    namespaces: [] # Only report events from these namespaces
    excludeNamespaces: [] # Do not report events from these namespaces
    excludeComponents: [] # Do not report events from these components
    excludeReasons: [] # Do not report events with these reasons
    eventLevels: [ 'warning', 'error' ] # Only report events of these levels. "error" events are always reported.

# Sentry DSN config using an existing secret:
# existingSecret:
image:
  repository: ghcr.io/alekitto/sentry-kubernetes
  tag: latest
  pullPolicy: Always

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Set priorityCLassName in deployment
# priorityClassName: ""

podLabels: {}
podAnnotations: {}
