apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "sentry-kubernetes.labels" . | indent 4 }}
  name: {{ template "sentry-kubernetes.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sentry-kubernetes.name" . }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry-kubernetes.name" . }}
        release: {{.Release.Name }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        args:
          - -c
          - /app/config.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: {{ template "sentry-kubernetes.secretName" . }}
                key: sentry.dsn
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - mountPath: /app/config.yaml
            name: app-config
            subPath: config.yaml
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: {{ template "sentry-kubernetes.serviceAccountName" . }}
      volumes:
        - name: app-config
          configMap:
            name: {{ template "sentry-kubernetes.fullname" . }}
