name: build

on:
    push:
        branches:
            - 'develop'
        tags:
            - 'v*'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.ref }}-build-chart
    cancel-in-progress: true

jobs:
    build:
        name: Build Helm chart
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 1

            - name: Push Helm chart to OCI compatible registry (Github)
              uses: bsord/helm-push@v4
              with:
                  useOCIRegistry: true
                  registry-url:  oci://ghcr.io/${{ github.repository }}-chart
                  username: ${{ github.actor }}
                  access-token: ${{ secrets.GITHUB_TOKEN }}
                  chart-folder: chart
